### ISSUE TITLE
deprecated code which not work anymore

### ISSUE THREAD

**Issue by eli-chen** [Code-Pop/Real-World-Vue-3-New-Syntax#4]
start with vue router 4.1.4 it's not possible anymore to send stuff through route params
so the code in `EventCard.vue` will not work
```
  <RouterLink
    class="event-link"
    :to="{ name: 'event-details', params: { id: event.id } }"
  >
```
more info on that feature which removed can be found here
[[4.1.4](https://github.com/vuejs/router/compare/v4.1.3...v4.1.4)](https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22)

also the video about this should be changed or at least note that in description over there

**Comment by tutorialcode** [comment]
> start with vue router 4.1.4 it's not possible anymore to send stuff through route params
> 
> so the code in `EventCard.vue` will not work
> 
> ```
> 
>   <RouterLink
> 
>     class="event-link"
> 
>     :to="{ name: 'event-details', params: { id: event.id } }"
> 
>   >
> 
> ```
> 
> more info on that feature which removed can be found here
> 
> [[4.1.4](https://github.com/vuejs/router/compare/v4.1.3...v4.1.4)](https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22)
> 
> 
> 
> also the video about this should be changed or at least note that in description over there
> 
> 

It says it would not work if the param is not defined as part of the path. The EventDetailsView path is defined with the :id param.
